//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecuritySystemContext : DbContext
    {
        public SecuritySystemContext()
            : base("name=SecuritySystemContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vTrafficByUser> vTrafficByUsers { get; set; }
        public virtual DbSet<SmsTask> SmsTasks { get; set; }
        public virtual DbSet<SmsTasksByPassPoint> SmsTasksByPassPoints { get; set; }
    }
}
