//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTrafficByUser
    {
        public Nullable<int> UserId { get; set; }
        public int OriginalId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string Description { get; set; }
        public Nullable<int> Door { get; set; }
        public int id { get; set; }
        public Nullable<bool> IsEntry { get; set; }
        public Nullable<bool> FromCodas { get; set; }
        public Nullable<bool> DoorIsEntry { get; set; }
        public string DoorDesc { get; set; }
        public string Alias { get; set; }
    }
}
